### ISSUE TITLE
Windows 11 offered in Release Preview

### ISSUE THREAD

**Issue by dongle-the-gadget** [uup-dump/api#16]
Using fetchupd.php with channel Release Preview returns Windows 11 for some reaon.

**Reproducing:** https://api.uupdump.net/fetchupd.php?arch=amd64&ring=rp
**Expected:** Windows 10 21H2 build 19044
**Actual:** Windows 11 build 22000

**Comment by abbodi1406** [comment]
You must specify **build**, otherwise **latest** is used, which is currently 22000

and build 19044 is not currently available with Release Preview channel under usual circumstances, so you must specify it to get it
https://api.uupdump.net/fetchupd.php?arch=amd64&ring=rp&build=19044.1

**Comment by dongle-the-gadget** [comment]
Alright then.
