### ISSUE TITLE
Bug - create ISO file (W10ARM - 18362.175)

### ISSUE THREAD

**Issue by erura** [uup-dump/api#2]
Making ISO file from latest release of Windows 10 ARM (Feature or Cumulative 18362.175 arm64) ends with error. Please see below screenshot.

![IMG_20190614_091349_807](https://user-images.githubusercontent.com/2844032/59490512-2d1a3e80-8e85-11e9-8f5d-b78bdb345eca.jpg)

**Comment by whatever127** [comment]
This seems to be a Windows converter related issue.

**Comment by whatever127** [comment]
The issue has been fixed by the Windows UUP converter author.
