### ISSUE TITLE
#UUPDUMP_ERROR:EMPTY_FILELIST (only affecting all releases of 15063 / RS2 / Version 1703)

### ISSUE THREAD

**Issue by starchivore** [uup-dump/api#6]
Good Day,

As reported here, we're experiencing some issues with everything related 15063 / RS2 / Version 1703 recently:

[https://forums.mydigitallife.net/posts/1607061](https://forums.mydigitallife.net/posts/1607061)

I verified 3 different releases as listed below, first one (i.e. **uupdump.ml**) was showing **#UUPDUMP_ERROR:EMPTY_FILELIST** consistently while second one (i.e. **uup.rg-adguard.net**) seemed to be OK so far:

> Windows 10 Insider Preview 15063.543 (rs2_release_svc_d_shub) amd64
> [https://uupdump.ml/get.php?id=b304b230-c3d2-44da-bb85-b8bd4c16d1e6&pack=en-us&edition=ppipro&aria2=2](https://uupdump.ml/get.php?id=b304b230-c3d2-44da-bb85-b8bd4c16d1e6&pack=en-us&edition=ppipro&aria2=2)
> [https://uup.rg-adguard.net/api/GetFiles?id=b304b230-c3d2-44da-bb85-b8bd4c16d1e6&lang=en-us&edition=ppipro&txt=yes](https://uup.rg-adguard.net/api/GetFiles?id=b304b230-c3d2-44da-bb85-b8bd4c16d1e6&lang=en-us&edition=ppipro&txt=yes)

> Windows 10 Insider Preview 15063.542 (rs2_release_svc_d_shub) amd64
> [https://uupdump.ml/get.php?id=88a062af-306a-4cd7-9b8e-f3c168dd8b14&pack=en-us&edition=ppipro&aria2=2](https://uupdump.ml/get.php?id=88a062af-306a-4cd7-9b8e-f3c168dd8b14&pack=en-us&edition=ppipro&aria2=2)
> [https://uup.rg-adguard.net/api/GetFiles?id=88a062af-306a-4cd7-9b8e-f3c168dd8b14&lang=en-us&edition=ppipro&txt=yes](https://uup.rg-adguard.net/api/GetFiles?id=88a062af-306a-4cd7-9b8e-f3c168dd8b14&lang=en-us&edition=ppipro&txt=yes)

> Windows 10 Insider Preview 15063 (rs2_release) amd64
> [https://uupdump.ml/get.php?id=d89ce75a-6769-42fb-bd43-16e6c3758479&pack=en-us&edition=core&aria2=2](https://uupdump.ml/get.php?id=d89ce75a-6769-42fb-bd43-16e6c3758479&pack=en-us&edition=core&aria2=2)
> [https://uup.rg-adguard.net/api/GetFiles?id=d89ce75a-6769-42fb-bd43-16e6c3758479&lang=en-us&edition=Core&txt=yes](https://uup.rg-adguard.net/api/GetFiles?id=d89ce75a-6769-42fb-bd43-16e6c3758479&lang=en-us&edition=Core&txt=yes)

Then I went through everything (16299 17134 17763 18362 18363 19041 19042) afterwards and all of them were working fine, even the latest IP was good to go:

> Windows 10 Insider Preview 20161.1000 (rs_prerelease) amd64
> [https://uupdump.ml/get.php?id=d44ba488-9897-4114-95cb-71c5bb94d787&pack=en-us&edition=core&aria2=2](https://uupdump.ml/get.php?id=d44ba488-9897-4114-95cb-71c5bb94d787&pack=en-us&edition=core&aria2=2)
> [https://uup.rg-adguard.net/api/GetFiles?id=d44ba488-9897-4114-95cb-71c5bb94d787&lang=en-us&edition=Core&txt=yes](https://uup.rg-adguard.net/api/GetFiles?id=d44ba488-9897-4114-95cb-71c5bb94d787&lang=en-us&edition=Core&txt=yes)

I also tried everything again on my seed box (different geo location) and the same issues were replicated, just wondering if there were any changes applied earlier that might have broken all releases of 15063 by any chance? Thanks a lot.

**Comment by awuctl** [comment]
Thank you for bringing this to our attention. I reverted the recent changes to the API from 139838b42edf039275280f23cf3cb09fb61dbec6 in 4ee4df622612a43fc03bb24d497557ebe6ec8fc7 and everything seems to work fine now.
I'll ask the author of those changes to fix backwards compatibility ASAP and re-add the changes. Thanks again for the report.
